name: test_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^0.3.2
  circular_reveal_animation: ^2.0.0
  auto_size_text_field: ^1.0.1
  carousel_slider: ^4.0.0
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
